/*
 * =============================================================================
 * 
 *   Copyright (c) 2008, The JAVAGALICIAN team (http://www.javagalician.org)
 * 
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 * 
 * =============================================================================
 */
package org.javagalician.text;

import java.text.DateFormatSymbols;

import org.javagalician.constants.Locales;

public final class GalicianDateFormatSymbols extends DateFormatSymbols {
    
    private static final long serialVersionUID = 6772605910726027718L;
    
    
    private static final String[] GALICIAN_MONTHS = 
        {"xaneiro", "febreiro", "marzo", "abril", "maio", "xu\u00F1o", "xullo", 
        "agosto", "setembro", "outubro", "novembro", "decembro", ""};

    private static final String[] GALICIAN_SHORT_MONTHS = 
        {"xan", "feb", "mar", "abr", "mai", "xu\u00F1", "xul", 
        "ago", "set", "out", "nov", "dec", ""};

    private static final String[] GALICIAN_SHORT_WEEKDAYS = 
        {"", "dom", "lun", "mar", "m\u00E9r", "xov", "ven", "s\u00E1b"};

    private static final String[] GALICIAN_WEEKDAYS = 
        {"", "domingo", "luns", "martes", "m\u00E9rcores", "xoves", "venres", "s\u00E1bado"};
    
    private static final String[][] GALICIAN_ZONE_STRINGS =
        {
            {"America/Los_Angeles", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"PST", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Denver", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"MST", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Phoenix", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"PNT", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Chicago", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"CST", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/New_York", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"EST", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indianapolis", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"IET", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"Pacific/Honolulu", "Hora est\u00E1ndar de Hawaii", "HST", "Hora de ver\u00E1n de Hawaii", "HDT"},
            {"HST", "Hora est\u00E1ndar de Hawaii", "HST", "Hora de ver\u00E1n de Hawaii", "HDT"},
            {"America/Anchorage", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"AST", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"America/Halifax", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/St_Johns", "Hora est\u00E1ndar de Terranova", "NST", "Hora de ver\u00E1n de Terranova", "NDT"},
            {"CNT", "Hora est\u00E1ndar de Terranova", "NST", "Hora de ver\u00E1n de Terranova", "NDT"},
            {"Europe/Paris", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"ECT", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"GMT", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Casablanca", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Asia/Jerusalem", "Hora est\u00E1ndar de Israel", "IST", "Hora de ver\u00E1n de Israel", "IDT"},
            {"Asia/Tokyo", "Hora est\u00E1ndar de Xap\u00F3n", "JST", "Hora de ver\u00E1n de Xap\u00F3n", "JDT"},
            {"JST", "Hora est\u00E1ndar de Xap\u00F3n", "JST", "Hora de ver\u00E1n de Xap\u00F3n", "JDT"},
            {"Europe/Bucharest", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Shanghai", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"CTT", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"ACT", "Hora est\u00E1ndar Central (territorio do Norte)", "CST", "Hora de ver\u00E1n Central (territorio do Norte)", "CST"},
            {"AET", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"AGT", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"ART", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Africa/Abidjan", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Accra", "Hora central de Ghana", "GMT", "Hora de ver\u00E1n de Ghana", "GHST"},
            {"Africa/Addis_Ababa", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Algiers", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Africa/Asmara", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Asmera", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Bamako", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Bangui", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Banjul", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Bissau", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Blantyre", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Brazzaville", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Bujumbura", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Cairo", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Africa/Ceuta", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Africa/Conakry", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Dakar", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Dar_es_Salaam", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Djibouti", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Douala", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/El_Aaiun", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Africa/Freetown", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Serra Leona", "SLST"},
            {"Africa/Gaborone", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Harare", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Johannesburg", "Hora est\u00E1ndar de Sud\u00E1frica", "SAST", "Hora de ver\u00E1n de Sud\u00E1frica", "SAST"},
            {"Africa/Kampala", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Khartoum", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Kigali", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Kinshasa", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Lagos", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Libreville", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Lome", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Luanda", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Lubumbashi", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Lusaka", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Malabo", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Maputo", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"Africa/Maseru", "Hora est\u00E1ndar de Sud\u00E1frica", "SAST", "Hora de ver\u00E1n de Sud\u00E1frica", "SAST"},
            {"Africa/Mbabane", "Hora est\u00E1ndar de Sud\u00E1frica", "SAST", "Hora de ver\u00E1n de Sud\u00E1frica", "SAST"},
            {"Africa/Mogadishu", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Monrovia", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Nairobi", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Africa/Ndjamena", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Niamey", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Nouakchott", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Ouagadougou", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Porto-Novo", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"Africa/Sao_Tome", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Timbuktu", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Africa/Tripoli", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Africa/Tunis", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Africa/Windhoek", "Hora de \u00C1frica Occidental", "WAT", "Hora de ver\u00E1n de \u00C1frica Occidental", "WAST"},
            {"America/Adak", "Hora est\u00E1ndar de Hawaii-Aleutianas", "HAST", "Hora de ver\u00E1n de Hawaii-Aleutianas", "HADT"},
            {"America/Anguilla", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Antigua", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Araguaina", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Argentina/Buenos_Aires", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Catamarca", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/ComodRivadavia", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Cordoba", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Jujuy", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/La_Rioja", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Mendoza", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Rio_Gallegos", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Salta", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/San_Juan", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/San_Luis", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Tucuman", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Argentina/Ushuaia", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Aruba", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Asuncion", "Hora do Paraguai", "PYT", "Hora de ver\u00E1n do Paraguai", "PYST"},
            {"America/Atikokan", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Atka", "Hora est\u00E1ndar de Hawaii-Aleutianas", "HAST", "Hora de ver\u00E1n de Hawaii-Aleutianas", "HADT"},
            {"America/Bahia", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Barbados", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Belem", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Belize", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Blanc-Sablon", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Boa_Vista", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Bogota", "Hora de Colombia", "COT", "Hora de ver\u00E1n de Colombia", "COST"},
            {"America/Boise", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Buenos_Aires", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Cambridge_Bay", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Campo_Grande", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Cancun", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Caracas", "Hora de Venezuela", "VET", "Hora de ver\u00E1n de Venezuela", "VEST"},
            {"America/Catamarca", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Cayenne", "Hora da Guayana Francesa", "GFT", "Hora de ver\u00E1n da Guayana Francesa", "GFST"},
            {"America/Cayman", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Chihuahua", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Coral_Harbour", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Cordoba", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Costa_Rica", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Cuiaba", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Curacao", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Danmarkshavn", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"America/Dawson", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Dawson_Creek", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Detroit", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Dominica", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Edmonton", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Eirunepe", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/El_Salvador", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Ensenada", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Fort_Wayne", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Fortaleza", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Glace_Bay", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Godthab", "Hora de Groenlandia Occidental", "WGT", "Hora de ver\u00E1n de Groenlandia Occidental", "WGST"},
            {"America/Goose_Bay", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Grand_Turk", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Grenada", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Guadeloupe", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Guatemala", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Guayaquil", "Hora de Ecuador", "ECT", "Hora de ver\u00E1n de Ecuador", "ECST"},
            {"America/Guyana", "Hora de Guyana", "GYT", "Hora de ver\u00E1n de Guyana", "GYST"},
            {"America/Havana", "Hora de Cuba", "CST", "Hora de ver\u00E1n de Cuba", "CDT"},
            {"America/Hermosillo", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Indiana/Indianapolis", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indiana/Knox", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Indiana/Marengo", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indiana/Petersburg", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indiana/Tell_City", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Indiana/Vevay", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indiana/Vincennes", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Indiana/Winamac", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Inuvik", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Iqaluit", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Jamaica", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Jujuy", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Juneau", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"America/Kentucky/Louisville", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Kentucky/Monticello", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Knox_IN", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/La_Paz", "Hora de Bolivia", "BOT", "Hora de ver\u00E1n de Bolivia", "BOST"},
            {"America/Lima", "Hora do Per\u00FA", "PET", "Hora de ver\u00E1n do Per\u00FA", "PEST"},
            {"America/Louisville", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Maceio", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Managua", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Manaus", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Marigot", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Martinique", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Mazatlan", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/Mendoza", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Menominee", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Merida", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Mexico_City", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Miquelon", "Hora est\u00E1ndar de Pierre & Miquelon", "PMST", "Hora de ver\u00E1n de Pierre & Miquelon", "PMDT"},
            {"America/Moncton", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Montevideo", "Hora do Uruguai", "UYT", "Hora de ver\u00E1n do Uruguai", "UYST"},
            {"America/Monterrey", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Montreal", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Montserrat", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Nassau", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Nipigon", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Nome", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"America/Noronha", "Hora de Fernando de Noronha", "FNT", "Hora de ver\u00E1n de Fernando de Noronha", "FNST"},
            {"America/North_Dakota/Center", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/North_Dakota/New_Salem", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Panama", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Pangnirtung", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Paramaribo", "Hora de Surinam", "SRT", "Hora de ver\u00E1n de Surinam", "SRST"},
            {"America/Port-au-Prince", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Port_of_Spain", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Porto_Acre", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Porto_Velho", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Puerto_Rico", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Rainy_River", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Rankin_Inlet", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Recife", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Regina", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Resolute", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Rio_Branco", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"America/Rosario", "Hora da Arxentina", "ART", "Hora de ver\u00E1n da Arxentina", "ARST"},
            {"America/Santarem", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Santiago", "Hora de Chile", "CLT", "Hora de ver\u00E1n de Chile", "CLST"},
            {"America/Santo_Domingo", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Sao_Paulo", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"America/Scoresbysund", "Hora de Groenlandia Oriental", "EGT", "Hora de ver\u00E1n de Groenlandia Oriental", "EGST"},
            {"America/Shiprock", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"America/St_Barthelemy", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/St_Kitts", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/St_Lucia", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/St_Thomas", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/St_Vincent", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Swift_Current", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Tegucigalpa", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Thule", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Thunder_Bay", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Tijuana", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Toronto", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"America/Tortola", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Vancouver", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Virgin", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"America/Whitehorse", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"America/Winnipeg", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"America/Yakutat", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"America/Yellowknife", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"Antarctica/Casey", "Hora est\u00E1ndar Occidental (Australia)", "WST", "Hora de ver\u00E1n Occidental (Australia)", "WST"},
            {"Antarctica/Davis", "Hora de Davis", "DAVT", "Hora de ver\u00E1n de Davis", "DAVST"},
            {"Antarctica/DumontDUrville", "Hora de Dumont-d'Urville", "DDUT", "Hora de ver\u00E1n de Dumont-d'Urville", "DDUST"},
            {"Antarctica/Mawson", "Hora de Mawson", "MAWT", "Hora de ver\u00E1n de Mawson", "MAWST"},
            {"Antarctica/McMurdo", "Hora est\u00E1ndar de Nova Zelanda", "NZST", "Hora de ver\u00E1n de Nova Zelanda", "NZDT"},
            {"Antarctica/Palmer", "Hora de Chile", "CLT", "Hora de ver\u00E1n de Chile", "CLST"},
            {"Antarctica/Rothera", "Hora de Rothera", "ROTT", "Hora de ver\u00E1n de Rothera", "ROTST"},
            {"Antarctica/South_Pole", "Hora est\u00E1ndar de Nova Zelanda", "NZST", "Hora de ver\u00E1n de Nova Zelanda", "NZDT"},
            {"Antarctica/Syowa", "Hora de Syowa", "SYOT", "Hora de ver\u00E1n de Syowa", "SYOST"},
            {"Antarctica/Vostok", "Hora de Vostok", "VOST", "Hora de ver\u00E1n de Vostok", "VOSST"},
            {"Arctic/Longyearbyen", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Asia/Aden", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Almaty", "Hora de Alma-Ata", "ALMT", "Hora de ver\u00E1n de Alma-Ata", "ALMST"},
            {"Asia/Amman", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Anadyr", "Hora de Anadyr", "ANAT", "Hora de ver\u00E1n de Anadyr", "ANAST"},
            {"Asia/Aqtau", "Hora de Aqtau", "AQTT", "Hora de ver\u00E1n de Aqtau", "AQTST"},
            {"Asia/Aqtobe", "Hora de Aqtobe", "AQTT", "Hora de ver\u00E1n de Aqtobe", "AQTST"},
            {"Asia/Ashgabat", "Hora de Turkmenist\u00E1n", "TMT", "Hora de ver\u00E1n de Turkmenist\u00E1n", "TMST"},
            {"Asia/Ashkhabad", "Hora de Turkmenist\u00E1n", "TMT", "Hora de ver\u00E1n de Turkmenist\u00E1n", "TMST"},
            {"Asia/Baghdad", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Bahrain", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Baku", "Hora de Azerbaiy\u00E1n", "AZT", "Hora de ver\u00E1n de Azerbaiy\u00E1n", "AZST"},
            {"Asia/Bangkok", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"Asia/Beirut", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Bishkek", "Hora de Kirguizist\u00E1n", "KGT", "Hora de ver\u00E1n de Kirguizist\u00E1n", "KGST"},
            {"Asia/Brunei", "Hora de Brunei", "BNT", "Hora de ver\u00E1n de Brunei", "BNST"},
            {"Asia/Calcutta", "Hora est\u00E1ndar de India", "IST", "Hora de ver\u00E1n de India", "IDT"},
            {"Asia/Choibalsan", "Hora de Choibalsan", "CHOT", "Hora de ver\u00E1n de Choibalsan", "CHOST"},
            {"Asia/Chongqing", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Chungking", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Colombo", "Hora est\u00E1ndar de India", "IST", "Hora de ver\u00E1n de India", "IDT"},
            {"Asia/Dacca", "Hora de Bangladesh", "BDT", "Hora de ver\u00E1n de Bangladesh", "BDST"},
            {"Asia/Dhaka", "Hora de Bangladesh", "BDT", "Hora de ver\u00E1n de Bangladesh", "BDST"},
            {"Asia/Dili", "Hora de Timor Leste", "TLT", "Hora de ver\u00E1n de Timor Leste", "TLST"},
            {"Asia/Damascus", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Dubai", "Hora est\u00E1ndar do Golfo", "GST", "Hora de ver\u00E1n do Golfo", "GDT"},
            {"Asia/Dushanbe", "Hora de Tajikist\u00E1n", "TJT", "Hora de ver\u00E1n de Tajikist\u00E1n", "TJST"},
            {"Asia/Gaza", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Harbin", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Ho_Chi_Minh", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"Asia/Hong_Kong", "Hora de Hong Kong", "HKT", "Hora de ver\u00E1n de Hong Kong", "HKST"},
            {"Asia/Hovd", "Hora de Hovd", "HOVT", "Hora de ver\u00E1n de Hovd", "HOVST"},
            {"Asia/Irkutsk", "Hora de Irkutsk", "IRKT", "Hora de ver\u00E1n de Irkutsk", "IRKST"},
            {"Asia/Istanbul", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Jakarta", "Hora de Indonesia Occidental", "WIT", "Indonesia Hora de ver\u00E1n de Indonesia Occidental", "WIST"},
            {"Asia/Jayapura", "Hora de Indonesia Oriental", "EIT", "Hora de ver\u00E1n de Indonesia Oriental", "EIST"},
            {"Asia/Kabul", "Hora de Afganist\u00E1n", "AFT", "Hora de ver\u00E1n de Afganist\u00E1n", "AFST"},
            {"Asia/Kamchatka", "Hora de Petropavlovsk-Kamchatski", "PETT", "Hora de ver\u00E1n de Petropavlovsk-Kamchatski", "PETST"},
            {"Asia/Karachi", "Hora de Pakist\u00E1n", "PKT", "Hora de ver\u00E1n de Pakist\u00E1n", "PKST"},
            {"Asia/Kashgar", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Katmandu", "Hora de Nepal", "NPT", "Hora de ver\u00E1n de Nepal", "NPST"},
            {"Asia/Kolkata", "Hora est\u00E1ndar de India", "IST", "Hora de ver\u00E1n de India", "IDT"},
            {"Asia/Krasnoyarsk", "Hora de Krasnoyarsk", "KRAT", "Hora de ver\u00E1n de Krasnoyarsk", "KRAST"},
            {"Asia/Kuala_Lumpur", "Hora de Malasia", "MYT", "Hora de ver\u00E1n de Malasia", "MYST"},
            {"Asia/Kuching", "Hora de Malasia", "MYT", "Hora de ver\u00E1n de Malasia", "MYST"},
            {"Asia/Kuwait", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Macao", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Macau", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Magadan", "Hora de Magad\u00E1n", "MAGT", "Hora de ver\u00E1n de Magad\u00E1n", "MAGST"},
            {"Asia/Makassar", "Hora de Indonesia Central", "CIT", "Hora de ver\u00E1n de Indonesia Central", "CIST"},
            {"Asia/Manila", "Hora de Filipinas", "PHT", "Hora de ver\u00E1n de Filipinas", "PHST"},
            {"Asia/Muscat", "Hora est\u00E1ndar do Golfo", "GST", "Hora de ver\u00E1n do Golfo", "GDT"},
            {"Asia/Nicosia", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Asia/Novosibirsk", "Hora de Novosibirsk", "NOVT", "Hora de ver\u00E1n de Novosibirsk", "NOVST"},
            {"Asia/Oral", "Hora de Uralsk", "ORAT", "Hora de ver\u00E1n de Uralsk", "ORAST"},
            {"Asia/Omsk", "Hora de Omsk", "OMST", "Hora de ver\u00E1n de Omsk", "OMSST"},
            {"Asia/Phnom_Penh", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"Asia/Pontianak", "Hora de Indonesia Occidental", "WIT", "Indonesia Hora de ver\u00E1n de Indonesia Occidental", "WIST"},
            {"Asia/Pyongyang", "Hora est\u00E1ndar de Corea", "KST", "Hora de ver\u00E1n de Corea", "KDT"},
            {"Asia/Qatar", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Qyzylorda", "Hora de Qyzylorda", "QYZT", "Hora de ver\u00E1n de Qyzylorda", "QYZST"},
            {"Asia/Rangoon", "Hora de Myanmar", "MMT", "Hora de ver\u00E1n de Myanmar", "MMST"},
            {"Asia/Riyadh", "Hora est\u00E1ndar de Arabia", "AST", "Hora de ver\u00E1n de Arabia", "ADT"},
            {"Asia/Saigon", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"Asia/Sakhalin", "Hora de Sajalin", "SAKT", "Hora de ver\u00E1n de Sajalin", "SAKST"},
            {"Asia/Samarkand", "Hora de Uzbekist\u00E1n", "UZT", "Hora de ver\u00E1n de Uzbekist\u00E1n", "UZST"},
            {"Asia/Seoul", "Hora est\u00E1ndar de Corea", "KST", "Hora de ver\u00E1n de Corea", "KDT"},
            {"Asia/Singapore", "Hora de Singapur", "SGT", "Hora de ver\u00E1n de  Singapur", "SGST"},
            {"Asia/Taipei", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Tel_Aviv", "Hora est\u00E1ndar de Israel", "IST", "Hora de ver\u00E1n de Israel", "IDT"},
            {"Asia/Tashkent", "Hora de Uzbekist\u00E1n", "UZT", "Hora de ver\u00E1n de Uzbekist\u00E1n", "UZST"},
            {"Asia/Tbilisi", "Hora de Georgia", "GET", "Hora de ver\u00E1n de Georgia", "GEST"},
            {"Asia/Tehran", "Hora est\u00E1ndar de Ir\u00E1n", "IRST", "Hora de ver\u00E1n de Ir\u00E1n", "IRDT"},
            {"Asia/Thimbu", "Hora de But\u00E1n", "BTT", "Hora de ver\u00E1n de But\u00E1n", "BTST"},
            {"Asia/Thimphu", "Hora de But\u00E1n", "BTT", "Hora de ver\u00E1n de But\u00E1n", "BTST"},
            {"Asia/Ujung_Pandang", "Hora de Indonesia Central", "CIT", "Hora de ver\u00E1n de Indonesia Central", "CIST"},
            {"Asia/Ulaanbaatar", "Hora de Ulan Bator", "ULAT", "Hora de ver\u00E1n de Ulan Bator", "ULAST"},
            {"Asia/Ulan_Bator", "Hora de Ulan Bator", "ULAT", "Hora de ver\u00E1n de Ulan Bator", "ULAST"},
            {"Asia/Urumqi", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"Asia/Vientiane", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"Asia/Vladivostok", "Hora de Vladivostok", "VLAT", "Hora de ver\u00E1n de Vladivostok", "VLAST"},
            {"Asia/Yakutsk", "Hora de Yakutsk", "YAKT", "Hora de ver\u00E1n de Yakutsk", "YAKST"},
            {"Asia/Yekaterinburg", "Hora de Ekaterinburgo", "YEKT", "Hora de ver\u00E1n de Ekaterinburgo", "YEKST"},
            {"Asia/Yerevan", "Hora de Armenia", "AMT", "Hora de ver\u00E1n de Armenia", "AMST"},
            {"Atlantic/Azores", "Hora de Azores", "AZOT", "Hora de ver\u00E1n de Azores", "AZOST"},
            {"Atlantic/Bermuda", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"Atlantic/Canary", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Atlantic/Cape_Verde", "Hora de Cabo Verde", "CVT", "Hora de ver\u00E1n de Cabo Verde", "CVST"},
            {"Atlantic/Faeroe", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Atlantic/Faroe", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Atlantic/Jan_Mayen", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Atlantic/Madeira", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Atlantic/Reykjavik", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Atlantic/South_Georgia", "Hora est\u00E1ndar de Georgia do Sur", "GST", "Hora de ver\u00E1n de Georgia do Sur", "GDT"},
            {"Atlantic/St_Helena", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Atlantic/Stanley", "Hora das illas Malvinas", "FKT", "Hora de ver\u00E1n das illas Malvinas", "FKST"},
            {"Australia/ACT", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"Australia/Adelaide", "Hora est\u00E1ndar Central (Sur de Australia)", "CST", "Hora de ver\u00E1n Central (Sur de Australia)", "CST"},
            {"Australia/Brisbane", "Hora est\u00E1ndar do Leste (Queensland)", "EST", "Hora de ver\u00E1n do Leste (Queensland)", "EST"},
            {"Australia/Broken_Hill", "Hora est\u00E1ndar Central (Sur de Australia/Nova Gales do Sur)", "CST", "Hora de ver\u00E1n Central (Sur de Australia/Nova Gales do Sur)", "CST"},
            {"Australia/Canberra", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"Australia/Currie", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"Australia/Darwin", "Hora est\u00E1ndar Central (territorio do Norte)", "CST", "Hora de ver\u00E1n Central (territorio do Norte)", "CST"},
            {"Australia/Eucla", "Hora est\u00E1ndar Central-Occidental (Australia)", "CWST", "Hora de ver\u00E1n Central-Occidental (Australia)", "CWST"},
            {"Australia/Hobart", "Hora est\u00E1ndar do Leste (Tasmania)", "EST", "Hora de ver\u00E1n do Leste (Tasmania)", "EST"},
            {"Australia/LHI", "Hora est\u00E1ndar de Lord Howe", "LHST", "Hora de ver\u00E1n de Lord Howe", "LHST"},
            {"Australia/Lindeman", "Hora est\u00E1ndar do Leste (Queensland)", "EST", "Hora de ver\u00E1n do Leste (Queensland)", "EST"},
            {"Australia/Lord_Howe", "Hora est\u00E1ndar de Lord Howe", "LHST", "Hora de ver\u00E1n de Lord Howe", "LHST"},
            {"Australia/Melbourne", "Hora est\u00E1ndar do Leste (Victoria)", "EST", "Hora de ver\u00E1n do Leste (Victoria)", "EST"},
            {"Australia/North", "Hora est\u00E1ndar Central (territorio do Norte)", "CST", "Hora de ver\u00E1n Central (territorio do Norte)", "CST"},
            {"Australia/NSW", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"Australia/Perth", "Hora est\u00E1ndar Occidental (Australia)", "WST", "Hora de ver\u00E1n Occidental (Australia)", "WST"},
            {"Australia/Queensland", "Hora est\u00E1ndar do Leste (Queensland)", "EST", "Hora de ver\u00E1n do Leste (Queensland)", "EST"},
            {"Australia/South", "Hora est\u00E1ndar Central (Sur de Australia)", "CST", "Hora de ver\u00E1n Central (Sur de Australia)", "CST"},
            {"Australia/Sydney", "Hora est\u00E1ndar Oriental (Nova Gales do Sur)", "EST", "Hora de ver\u00E1n Oriental (Nova Gales do Sur)", "EST"},
            {"Australia/Tasmania", "Hora est\u00E1ndar do Leste (Tasmania)", "EST", "Hora de ver\u00E1n do Leste (Tasmania)", "EST"},
            {"Australia/Victoria", "Hora est\u00E1ndar do Leste (Victoria)", "EST", "Hora de ver\u00E1n do Leste (Victoria)", "EST"},
            {"Australia/West", "Hora est\u00E1ndar Occidental (Australia)", "WST", "Hora de ver\u00E1n Occidental (Australia)", "WST"},
            {"Australia/Yancowinna", "Hora est\u00E1ndar Central (Sur de Australia/Nova Gales do Sur)", "CST", "Hora de ver\u00E1n Central (Sur de Australia/Nova Gales do Sur)", "CST"},
            {"BET", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"BST", "Hora de Bangladesh", "BDT", "Hora de ver\u00E1n de Bangladesh", "BDST"},
            {"Brazil/Acre", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"Brazil/DeNoronha", "Hora de Fernando de Noronha", "FNT", "Hora de ver\u00E1n de Fernando de Noronha", "FNST"},
            {"Brazil/East", "Hora do Brasil", "BRT", "Hora de ver\u00E1n do Brasil", "BRST"},
            {"Brazil/West", "Hora est\u00E1ndar da Amazonia", "AMT", "Hora de ver\u00E1n da Amazonia", "AMST"},
            {"Canada/Atlantic", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"Canada/Central", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"Canada/East-Saskatchewan", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"Canada/Eastern", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"Canada/Mountain", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"Canada/Newfoundland", "Hora est\u00E1ndar de Terranova", "NST", "Hora de ver\u00E1n de Terranova", "NDT"},
            {"Canada/Pacific", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"Canada/Yukon", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"Canada/Saskatchewan", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"CAT", "Hora de \u00C1frica Central", "CAT", "Hora de ver\u00E1n de \u00C1frica Central", "CAST"},
            {"CET", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Chile/Continental", "Hora de Chile", "CLT", "Hora de ver\u00E1n de Chile", "CLST"},
            {"Chile/EasterIsland", "Hora da Illa de Pascua", "EAST", "Hora de ver\u00E1n da Illa de Pascua", "EASST"},
            {"CST6CDT", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"Cuba", "Hora est\u00E1ndar de Cuba", "CST", "Hora de ver\u00E1n de Cuba", "CDT"},
            {"EAT", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"EET", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Egypt", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Eire", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Irlanda", "IST"},
            {"EST5EDT", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"Etc/Greenwich", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Etc/UCT", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"Etc/Universal", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"Etc/UTC", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"Etc/Zulu", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"Europe/Amsterdam", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Andorra", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Athens", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Belfast", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Europe/Belgrade", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Berlin", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Bratislava", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Brussels", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Budapest", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Chisinau", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Copenhagen", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Dublin", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Irlanda", "IST"},
            {"Europe/Gibraltar", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Guernsey", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Europe/Helsinki", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Isle_of_Man", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Europe/Istanbul", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Jersey", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Europe/Kaliningrad", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Kiev", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Lisbon", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Europe/Ljubljana", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/London", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Europe/Luxembourg", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Madrid", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Malta", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Mariehamn", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Minsk", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Monaco", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Moscow", "Hora est\u00E1ndar de Moscova", "MSK", "Hora de ver\u00E1n de Moscova", "MSD"},
            {"Europe/Nicosia", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Oslo", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Podgorica", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Prague", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Riga", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Rome", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Samara", "Hora de Samara", "SAMT", "Hora de ver\u00E1n de Samara", "SAMST"},
            {"Europe/San_Marino", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Sarajevo", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Simferopol", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Skopje", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Sofia", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Stockholm", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Tallinn", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Tirane", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Tiraspol", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Uzhgorod", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Vaduz", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Vatican", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Vienna", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Vilnius", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Volgograd", "Hora de Volgogrado", "VOLT", "Hora de ver\u00E1n de Volgogrado", "VOLST"},
            {"Europe/Warsaw", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Zagreb", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"Europe/Zaporozhye", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"Europe/Zurich", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"GB", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"GB-Eire", "Hora do Meridiano de Greenwich", "GMT", "Hora de ver\u00E1n de Gran Breta\u00F1a", "BST"},
            {"Greenwich", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Hongkong", "Hora de Hong Kong", "HKT", "Hora de ver\u00E1n de Hong Kong", "HKST"},
            {"Iceland", "Hora do Meridiano de Greenwich", "GMT", "Hora do Meridiano de Greenwich", "GMT"},
            {"Iran", "Hora est\u00E1ndar de Ir\u00E1n", "IRST", "Hora de ver\u00E1n de Ir\u00E1n", "IRDT"},
            {"IST", "Hora est\u00E1ndar de India", "IST", "Hora de ver\u00E1n de India", "IDT"},
            {"Indian/Antananarivo", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Indian/Chagos", "Hora do Territorio do Oc\u00E9ano \u00CDndico", "IOT", "Hora de ver\u00E1n do Territorio do Oc\u00E9ano \u00CDndico", "IOST"},
            {"Indian/Christmas", "Hora da illa de Christmas", "CXT", "Hora de ver\u00E1n da illa de Christmas", "CXST"},
            {"Indian/Cocos", "Hora das illas Cocos", "CCT", "Hora de ver\u00E1n das illas Cocos", "CCST"},
            {"Indian/Comoro", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Indian/Kerguelen", "Hora dos Territorios Franceses do Sur e da Ant\u00E1rtida", "TFT", "Hora de ver\u00E1n dos Territorios Franceses do Sur e da Ant\u00E1rtida", "TFST"},
            {"Indian/Mahe", "Hora de Seychelles", "SCT", "Hora de ver\u00E1n de Seychelles", "SCST"},
            {"Indian/Maldives", "Hora de Maldivas", "MVT", "Hora de ver\u00E1n de Maldivas", "MVST"},
            {"Indian/Mauritius", "Hora de Mauricio", "MUT", "Hora de ver\u00E1n de Mauricio", "MUST"},
            {"Indian/Mayotte", "Hora de \u00C1frica Oriental", "EAT", "Hora de ver\u00E1n de \u00C1frica Oriental", "EAST"},
            {"Indian/Reunion", "Hora de Reuni\u00F3n", "RET", "Hora de ver\u00E1n de Reuni\u00F3n", "REST"},
            {"Israel", "Hora est\u00E1ndar de Israel", "IST", "Hora de ver\u00E1n de Israel", "IDT"},
            {"Jamaica", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"Japan", "Hora est\u00E1ndar de Xap\u00F3n", "JST", "Hora de ver\u00E1n de Xap\u00F3n", "JDT"},
            {"Kwajalein", "Hora das Illas Marshall", "MHT", "Hora de ver\u00E1n das Illas Marshall", "MHST"},
            {"Libya", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"MET", "Hora de Europa Central", "MET", "Hora de ver\u00E1n de Europa Central", "MEST"},
            {"Mexico/BajaNorte", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"Mexico/BajaSur", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"Mexico/General", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"MIT", "Hora de Samoa Occidental", "WST", "Hora de ver\u00E1n de Samoa Occidental", "WSST"},
            {"MST7MDT", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"Navajo", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"NET", "Hora de Armenia", "AMT", "Hora de ver\u00E1n de Armenia", "AMST"},
            {"NST", "Hora est\u00E1ndar de Nova Zelanda", "NZST", "Hora de ver\u00E1n de Nova Zelanda", "NZDT"},
            {"NZ", "Hora est\u00E1ndar de Nova Zelanda", "NZST", "Hora de ver\u00E1n de Nova Zelanda", "NZDT"},
            {"NZ-CHAT", "Hora est\u00E1ndar de Chatham", "CHAST", "Hora de ver\u00E1n de Chatham", "CHADT"},
            {"PLT", "Hora de Pakist\u00E1n", "PKT", "Hora de ver\u00E1n de Pakist\u00E1n", "PKST"},
            {"Portugal", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"PRT", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"Pacific/Apia", "Hora de Samoa Occidental", "WST", "Hora de ver\u00E1n de Samoa Occidental", "WSST"},
            {"Pacific/Auckland", "Hora est\u00E1ndar de Nova Zelanda", "NZST", "Hora de ver\u00E1n de Nova Zelanda", "NZDT"},
            {"Pacific/Chatham", "Hora est\u00E1ndar de Chatham", "CHAST", "Hora de ver\u00E1n de Chatham", "CHADT"},
            {"Pacific/Easter", "Hora da Illa de Pascua", "EAST", "Hora de ver\u00E1n da Illa de Pascua", "EASST"},
            {"Pacific/Efate", "Hora de Vanuatu", "VUT", "Hora de ver\u00E1n de Vanuatu", "VUST"},
            {"Pacific/Enderbury", "Hora da illa Phoenix", "PHOT", "Hora de ver\u00E1n da illa Phoenix", "PHOST"},
            {"Pacific/Fakaofo", "Hora de Tokelau", "TKT", "Hora de ver\u00E1n de Tokelau", "TKST"},
            {"Pacific/Fiji", "Hora de Fiji", "FJT", "Hora de ver\u00E1n de Fiji", "FJST"},
            {"Pacific/Funafuti", "Hora de Tuvalu", "TVT", "Hora de ver\u00E1n de Tuvalu", "TVST"},
            {"Pacific/Galapagos", "Hora de Gal\u00E1pagos", "GALT", "Hora de ver\u00E1n de Gal\u00E1pagos", "GALST"},
            {"Pacific/Gambier", "Hora de Gambier", "GAMT", "Hora de ver\u00E1n de Gambier", "GAMST"},
            {"Pacific/Guadalcanal", "Hora das Illas Solomon", "SBT", "Hora de ver\u00E1n das Illas Solomon", "SBST"},
            {"Pacific/Guam", "Hora est\u00E1ndar de Chamorro", "ChST", "Hora de ver\u00E1n de Chamorro", "ChDT"},
            {"Pacific/Johnston", "Hora est\u00E1ndar de Hawaii", "HST", "Hora de ver\u00E1n de Hawaii", "HDT"},
            {"Pacific/Kiritimati", "Hora das illas Line", "LINT", "Hora de ver\u00E1n das illas Line", "LINST"},
            {"Pacific/Kosrae", "Hora de Kosrae", "KOST", "Hora de ver\u00E1n de Kosrae", "KOSST"},
            {"Pacific/Kwajalein", "Hora das Illas Marshall", "MHT", "Hora de ver\u00E1n das Illas Marshall", "MHST"},
            {"Pacific/Majuro", "Hora das Illas Marshall", "MHT", "Hora de ver\u00E1n das Illas Marshall", "MHST"},
            {"Pacific/Marquesas", "Hora de Marquesas", "MART", "Hora de ver\u00E1n de Marquesas", "MARST"},
            {"Pacific/Midway", "Hora est\u00E1ndar de Samoa", "SST", "Hora de ver\u00E1n de Samoa", "SDT"},
            {"Pacific/Nauru", "Hora de Nauru", "NRT", "Hora de ver\u00E1n de Nauru", "NRST"},
            {"Pacific/Niue", "Hora de Niue", "NUT", "Hora de ver\u00E1n de Niue", "NUST"},
            {"Pacific/Norfolk", "Hora de Norfolk", "NFT", "Hora de ver\u00E1n de Norfolk", "NFST"},
            {"Pacific/Noumea", "Hora de Nova Caledonia", "NCT", "Hora de ver\u00E1n de Nova Caledonia", "NCST"},
            {"Pacific/Pago_Pago", "Hora est\u00E1ndar de Samoa", "SST", "Hora de ver\u00E1n de Samoa", "SDT"},
            {"Pacific/Palau", "Hora de Palau", "PWT", "Hora de ver\u00E1n de Palau", "PWST"},
            {"Pacific/Pitcairn", "Hora est\u00E1ndar de Pitcairn", "PST", "Hora de ver\u00E1n de Pitcairn", "PDT"},
            {"Pacific/Ponape", "Hora de Ponape", "PONT", "Hora de ver\u00E1n de Ponape", "PONST"},
            {"Pacific/Port_Moresby", "Hora de Pap\u00FAa-Nova Guinea", "PGT", "Hora de ver\u00E1n de Pap\u00FAa-Nova Guinea", "PGST"},
            {"Pacific/Rarotonga", "Hora das illas Cook", "CKT", "Hora de ver\u00E1n das illas Cook", "CKHST"},
            {"Pacific/Saipan", "Hora est\u00E1ndar de Chamorro", "ChST", "Hora de ver\u00E1n de Chamorro", "ChDT"},
            {"Pacific/Samoa", "Hora est\u00E1ndar de Samoa", "SST", "Hora de ver\u00E1n de Samoa", "SDT"},
            {"Pacific/Tahiti", "Hora de Tahit\u00ED", "TAHT", "Hora de ver\u00E1n de Tahit\u00ED", "TAHST"},
            {"Pacific/Tarawa", "Hora das illas Gilbert", "GILT", "Hora de ver\u00E1n das illas Gilbert", "GILST"},
            {"Pacific/Tongatapu", "Hora de Tonga", "TOT", "Hora de ver\u00E1n de Tonga", "TOST"},
            {"Pacific/Truk", "Hora de Truk", "TRUT", "Hora de ver\u00E1n de Truk", "TRUST"},
            {"Pacific/Wake", "Hora de Wake", "WAKT", "Hora de ver\u00E1n de Wake", "WAKST"},
            {"Pacific/Wallis", "Hora de Wallis e Futuna", "WFT", "Hora de ver\u00E1n de Wallis e Futuna", "WFST"},
            {"Pacific/Yap", "Hora de Truk", "TRUT", "Hora de ver\u00E1n de Truk", "TRUST"},
            {"Poland", "Hora de Europa Central", "CET", "Hora de ver\u00E1n de Europa Central", "CEST"},
            {"PRC", "Hora est\u00E1ndar de China", "CST", "Hora de ver\u00E1n de China", "CDT"},
            {"PST8PDT", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"ROK", "Hora est\u00E1ndar de Corea", "KST", "Hora de ver\u00E1n de Corea", "KDT"},
            {"Singapore", "Hora de Singapur", "SGT", "Hora de ver\u00E1n de  Singapur", "SGST"},
            {"SST", "Hora das Illas Solomon", "SBT", "Hora de ver\u00E1n das Illas Solomon", "SBST"},
            {"SystemV/AST4", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"SystemV/AST4ADT", "Hora est\u00E1ndar Atl\u00E1ntico", "AST", "Hora de ver\u00E1n Atl\u00E1ntico", "ADT"},
            {"SystemV/CST6", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"SystemV/CST6CDT", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"SystemV/EST5", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"SystemV/EST5EDT", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"SystemV/HST10", "Hora est\u00E1ndar de Hawaii", "HST", "Hora de ver\u00E1n de Hawaii", "HDT"},
            {"SystemV/MST7", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"SystemV/MST7MDT", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"SystemV/PST8", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"SystemV/PST8PDT", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"SystemV/YST9", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"SystemV/YST9YDT", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"Turkey", "Hora de Europa Oriental", "EET", "Hora de ver\u00E1n de Europa Oriental", "EEST"},
            {"UCT", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"Universal", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"US/Alaska", "Hora est\u00E1ndar de Alaska", "AKST", "Hora de ver\u00E1n de Alaska", "AKDT"},
            {"US/Aleutian", "Hora est\u00E1ndar de Hawaii-Aleutianas", "HAST", "Hora de ver\u00E1n de Hawaii-Aleutianas", "HADT"},
            {"US/Arizona", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"US/Central", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"US/Eastern", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"US/Hawaii", "Hora est\u00E1ndar de Hawaii", "HST", "Hora de ver\u00E1n de Hawaii", "HDT"},
            {"US/Indiana-Starke", "Hora est\u00E1ndar Central", "CST", "Hora de ver\u00E1n Central", "CDT"},
            {"US/East-Indiana", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"US/Michigan", "Hora est\u00E1ndar Oriental", "EST", "Hora de ver\u00E1n Oriental", "EDT"},
            {"US/Mountain", "Hora est\u00E1ndar das Rochosas", "MST", "Hora de ver\u00E1n das Rochosas", "MDT"},
            {"US/Pacific", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"US/Pacific-New", "Hora est\u00E1ndar do Pac\u00EDfico", "PST", "Hora de ver\u00E1n do Pac\u00EDfico", "PDT"},
            {"US/Samoa", "Hora est\u00E1ndar de Samoa", "SST", "Hora de ver\u00E1n de Samoa", "SDT"},
            {"UTC", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"},
            {"VST", "Hora de Indochina", "ICT", "Hora de ver\u00E1n de Indochina", "ICST"},
            {"W-SU", "Hora est\u00E1ndar de Moscova", "MSK", "Hora de ver\u00E1n de Moscova", "MSD"},
            {"WET", "Hora de Europa Occidental", "WET", "Hora de ver\u00E1n de Europa Occidental", "WEST"},
            {"Zulu", "Hora Universal Coordinada", "UTC", "Hora Universal Coordinada", "UTC"}
        };

    
    
    
    
    public GalicianDateFormatSymbols() {
        super(Locales.CASTILIAN);
        this.setMonths(GALICIAN_MONTHS);
        this.setShortMonths(GALICIAN_SHORT_MONTHS);
        this.setShortWeekdays(GALICIAN_SHORT_WEEKDAYS);
        this.setWeekdays(GALICIAN_WEEKDAYS);
        this.setZoneStrings(GALICIAN_ZONE_STRINGS);
    }

}
